#!/usr/bin/env python3
"""Build the idea atlas from data/ideas.json.

Generates:
  ideas/<tier>/<ID>-<slug>.md          one card per idea
  ideas/README.md                      index tables, one per tier
  assets/charts/difficulty-novelty.svg unit chart: every idea placed by difficulty x novelty
  assets/charts/category-tiers.svg     stacked bars: ideas per category, split by tier
  README.md                            regions between <!-- BEGIN GENERATED:x --> markers

Usage:  python3 scripts/build.py          (build)
        python3 scripts/build.py --check  (validate data + fail if outputs are stale)
"""
from __future__ import annotations

import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "ideas.json"

TIERS = {
    "building-now": {"prefix": "B", "name": "Being built now", "short": "Building now",
                     "blurb": "Shipping or in active development in 2025–2026. Proven demand; the race is on execution."},
    "whitespace": {"prefix": "W", "name": "Whitespace", "short": "Whitespace",
                   "blurb": "Feasible on today's iPhone, but almost nobody is building it. The unclaimed ground."},
    "moonshot": {"prefix": "M", "name": "Moonshots", "short": "Moonshots",
                 "blurb": "Worth wanting, genuinely hard. Blocked by platform walls, trust, physics, or unsolved research."},
}
TIER_ORDER = list(TIERS)

# Categorical slots 1-3 of the validated reference palette (all-pairs safe in both modes).
TIER_COLORS = {
    "building-now": {"light": "#2a78d6", "dark": "#3987e5"},
    "whitespace": {"light": "#eb6834", "dark": "#d95926"},
    "moonshot": {"light": "#1baf7a", "dark": "#199e70"},
}

CATEGORIES = [
    "Life admin",
    "Money & commerce",
    "Health & body",
    "Mind & focus",
    "Family & care",
    "Work & business",
    "Learning & memory",
    "Physical world",
    "Social & communication",
    "Accessibility",
    "Safety & civic",
    "Creativity & media",
]

AUTONOMY = {
    "suggest": "L1 · Suggests, you act",
    "draft-approve": "L2 · Drafts, you approve",
    "act-report": "L3 · Acts in guardrails, reports back",
    "autonomous": "L4 · Runs long goals on its own",
}

HORIZONS = {
    "now": "Buildable now",
    "1-2y": "1–2 years",
    "3-5y": "3–5 years",
    "5y+": "5+ years",
}

SCORE_KEYS = ["difficulty", "novelty", "feasibility", "impact"]
SCORE_LABELS = {
    "difficulty": "Difficulty",
    "novelty": "Novelty",
    "feasibility": "Buildable on iOS today",
    "impact": "Impact if it works",
}

REQUIRED = [
    "id", "slug", "title", "tagline", "tier", "category", "moment", "problem",
    "loop", "ios_blocks", "hard_parts", "risks", "assumptions", "unknowns",
    "prior_art", "first_version", "scores", "horizon", "autonomy",
]
LOOP_KEYS = ["trigger", "senses", "decides", "checks_with_you", "acts", "remembers"]

GENERATED_NOTE = "<!-- Generated by scripts/build.py from data/ideas.json. Edit the JSON, then run the script. -->"


# --------------------------------------------------------------------------- data

def load() -> dict:
    with DATA.open(encoding="utf-8") as fh:
        return json.load(fh)


def validate(data: dict) -> list[str]:
    errs: list[str] = []
    ids, slugs = set(), set()
    for i, idea in enumerate(data["ideas"]):
        where = idea.get("id", f"#{i}")
        for key in REQUIRED:
            if key not in idea or idea[key] in (None, "", []):
                errs.append(f"{where}: missing '{key}'")
        if idea.get("tier") not in TIERS:
            errs.append(f"{where}: unknown tier {idea.get('tier')!r}")
        elif not str(idea.get("id", "")).startswith(TIERS[idea["tier"]]["prefix"] + "-"):
            errs.append(f"{where}: id must start with {TIERS[idea['tier']]['prefix']}- for tier {idea['tier']}")
        if idea.get("category") not in CATEGORIES:
            errs.append(f"{where}: unknown category {idea.get('category')!r}")
        if idea.get("autonomy") not in AUTONOMY:
            errs.append(f"{where}: unknown autonomy {idea.get('autonomy')!r}")
        if idea.get("horizon") not in HORIZONS:
            errs.append(f"{where}: unknown horizon {idea.get('horizon')!r}")
        for key in SCORE_KEYS:
            v = idea.get("scores", {}).get(key)
            if not isinstance(v, int) or not 1 <= v <= 5:
                errs.append(f"{where}: score {key} must be an int 1-5, got {v!r}")
        for key in LOOP_KEYS:
            if not idea.get("loop", {}).get(key):
                errs.append(f"{where}: loop.{key} missing")
        if not re.fullmatch(r"[a-z0-9]+(-[a-z0-9]+)*", idea.get("slug", "")):
            errs.append(f"{where}: slug must be kebab-case")
        if idea.get("id") in ids:
            errs.append(f"{where}: duplicate id")
        if idea.get("slug") in slugs:
            errs.append(f"{where}: duplicate slug")
        ids.add(idea.get("id"))
        slugs.add(idea.get("slug"))
        for p in idea.get("prior_art", []):
            if not isinstance(p, dict) or not p.get("name"):
                errs.append(f"{where}: prior_art entries need a name")
    return errs


def sort_key(idea: dict):
    return (TIER_ORDER.index(idea["tier"]), int(idea["id"].split("-")[1]))


def card_path(idea: dict) -> Path:
    return ROOT / "ideas" / idea["tier"] / f"{idea['id']}-{idea['slug']}.md"


def rel_card_link(idea: dict, from_dir: Path) -> str:
    return Path(__import__("os").path.relpath(card_path(idea), from_dir)).as_posix()


# ----------------------------------------------------------------------- markdown

def dots(v: int) -> str:
    return "●" * v + "○" * (5 - v)


def mermaid_label(text: str, width: int = 28) -> str:
    """Wrap a label for Mermaid and neutralize characters Mermaid treats as syntax."""
    text = text.replace('"', "'").replace("#", "no. ").replace(";", ",")
    words, lines, cur = text.split(), [], ""
    for w in words:
        if cur and len(cur) + 1 + len(w) > width:
            lines.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    if cur:
        lines.append(cur)
    return "<br/>".join(lines)


def loop_mermaid(loop: dict) -> str:
    L = {k: mermaid_label(loop[k]) for k in LOOP_KEYS}
    return "\n".join([
        "```mermaid",
        "flowchart LR",
        f'  T(["<b>Trigger</b><br/>{L["trigger"]}"]) --> S["<b>Senses</b><br/>{L["senses"]}"]',
        f'  S --> D{{"<b>Decides</b><br/>{L["decides"]}"}}',
        f'  D --> H[/"<b>Checks with you</b><br/>{L["checks_with_you"]}"/]',
        f'  H --> A["<b>Acts</b><br/>{L["acts"]}"]',
        f'  A --> M[("<b>Remembers</b><br/>{L["remembers"]}")]',
        "  M -. next time .-> S",
        "  classDef you fill:#fff4e5,stroke:#eb6834,color:#0b0b0b",
        "  classDef act fill:#e8f1fc,stroke:#2a78d6,color:#0b0b0b",
        "  class H you",
        "  class A act",
        "```",
    ])


def bullets(items: list[str]) -> str:
    return "\n".join(f"- {x}" for x in items)


def render_card(idea: dict, by_id: dict) -> str:
    tier = TIERS[idea["tier"]]
    s = idea["scores"]
    out = [GENERATED_NOTE, ""]
    out.append(f"[← All ideas](../README.md) · **{tier['name']}** · {idea['category']}")
    out.append("")
    out.append(f"# {idea['id']} · {idea['title']}")
    out.append("")
    out.append(f"> {idea['tagline']}")
    out.append("")
    out.append("| " + " | ".join(SCORE_LABELS[k] for k in SCORE_KEYS) + " | Horizon | Autonomy |")
    out.append("|" + "---|" * (len(SCORE_KEYS) + 2))
    out.append("| " + " | ".join(f"`{dots(s[k])}` {s[k]}/5" for k in SCORE_KEYS)
               + f" | {HORIZONS[idea['horizon']]} | {AUTONOMY[idea['autonomy']]} |")
    out.append("")
    if idea.get("mockup"):
        out.append(f"<p align=\"center\"><img src=\"../../{idea['mockup']}\" alt=\"Mockup: {html.escape(idea['title'])}\" width=\"320\"></p>")
        out.append("")
    out += ["## The moment", "", idea["moment"], ""]
    out += ["## The problem", "", idea["problem"], ""]
    out += ["## How the agent works", "", loop_mermaid(idea["loop"]), ""]
    if idea.get("deep_dive"):
        out += [idea["deep_dive"].strip(), ""]
    out += ["## iOS building blocks", ""]
    for b in idea["ios_blocks"]:
        if isinstance(b, dict):
            out.append(f"- **{b['name']}** — {b['why']}")
        else:
            out.append(f"- {b}")
    out.append("")
    out += ["## What makes it hard", "", bullets(idea["hard_parts"]), ""]
    out += ["## Risks and failure modes", "", bullets(idea["risks"]), ""]
    out += ["## Unsaid assumptions", "",
            "_What this idea quietly depends on being true. Check these before you build._", "",
            bullets(idea["assumptions"]), ""]
    out += ["## Unknown unknowns", "",
            "_Open questions nobody has good answers to yet._", "",
            bullets(idea["unknowns"]), ""]
    out += ["## Prior art and who's building", ""]
    for p in idea["prior_art"]:
        name = f"[{p['name']}]({p['url']})" if p.get("url") else p["name"]
        note = f" — {p['note']}" if p.get("note") else ""
        out.append(f"- {name}{note}")
    out.append("")
    out += ["## Smallest useful first version", "", idea["first_version"], ""]
    related = [by_id[r] for r in idea.get("related", []) if r in by_id]
    if related:
        out += ["## Related ideas", ""]
        for r in related:
            out.append(f"- [{r['id']} · {r['title']}](../{r['tier']}/{r['id']}-{r['slug']}.md)")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def index_table(ideas: list[dict], link_prefix: str) -> str:
    rows = ["| ID | Idea | Category | Difficulty | Novelty | Buildable today | Horizon |",
            "|---|---|---|---|---|---|---|"]
    for i in ideas:
        s = i["scores"]
        link = f"{link_prefix}{i['tier']}/{i['id']}-{i['slug']}.md"
        star = " ★" if i.get("flagship") else ""
        rows.append(f"| {i['id']} | [{i['title']}]({link}){star}<br/><sub>{i['tagline']}</sub> | {i['category']} "
                    f"| {s['difficulty']}/5 | {s['novelty']}/5 | {s['feasibility']}/5 | {HORIZONS[i['horizon']]} |")
    return "\n".join(rows)


def render_index(data: dict) -> str:
    ideas = sorted(data["ideas"], key=sort_key)
    out = [GENERATED_NOTE, "", "[← Back to the atlas](../README.md)", "", "# All ideas", ""]
    out.append(f"{len(ideas)} agentic iPhone app ideas in three tiers. ★ marks flagship ideas that get a deep dive and a mockup.")
    out.append("")
    out.append('<p align="center"><img src="../assets/charts/difficulty-novelty.svg" alt="Every idea placed by difficulty and novelty" width="100%"></p>')
    out.append("")
    for t in TIER_ORDER:
        group = [i for i in ideas if i["tier"] == t]
        out += [f"## {TIERS[t]['name']} ({len(group)})", "", f"_{TIERS[t]['blurb']}_", "", index_table(group, ""), ""]
    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------- SVG

SVG_FONT = "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Segoe UI', Helvetica, Arial, sans-serif"


def svg_style() -> str:
    light = "".join(f"--t-{t}: {c['light']};" for t, c in TIER_COLORS.items())
    dark = "".join(f"--t-{t}: {c['dark']};" for t, c in TIER_COLORS.items())
    return f"""<style>
  svg {{ --surface:#fcfcfb; --ink:#0b0b0b; --ink2:#52514e; --muted:#898781; --grid:#e1e0d9; --axis:#c3c2b7; {light} }}
  @media (prefers-color-scheme: dark) {{
    svg {{ --surface:#1a1a19; --ink:#ffffff; --ink2:#c3c2b7; --muted:#898781; --grid:#2c2c2a; --axis:#383835; {dark} }}
  }}
  text {{ font-family: {SVG_FONT}; }}
  .bg {{ fill: var(--surface); }}
  .title {{ fill: var(--ink); font-size: 20px; font-weight: 650; }}
  .sub {{ fill: var(--ink2); font-size: 13px; }}
  .axis-label {{ fill: var(--ink2); font-size: 13px; font-weight: 600; }}
  .tick {{ fill: var(--muted); font-size: 12px; }}
  .grid {{ stroke: var(--grid); stroke-width: 1; fill: none; }}
  .axis {{ stroke: var(--axis); stroke-width: 1; }}
  .legend {{ fill: var(--ink2); font-size: 13px; }}
  .val {{ fill: var(--ink2); font-size: 12px; font-variant-numeric: tabular-nums; }}
  .chip-text {{ font-size: 10.5px; font-weight: 650; fill: #0b0b0b; }}
  {''.join(f'.fill-{t} {{ fill: var(--t-{t}); }}' for t in TIER_COLORS)}
</style>"""


def legend(x: int, y: int) -> list[str]:
    parts, cx = [], x
    for t in TIER_ORDER:
        label = f"{TIERS[t]['prefix']}  {TIERS[t]['short']}"
        parts.append(f'<rect x="{cx}" y="{y - 10}" width="12" height="12" rx="3" class="fill-{t}"/>')
        parts.append(f'<text x="{cx + 18}" y="{y}" class="legend">{html.escape(label)}</text>')
        cx += 18 + int(len(label) * 7.4) + 24
    return parts


def chart_difficulty_novelty(data: dict) -> str:
    ideas = sorted(data["ideas"], key=sort_key)
    cells: dict[tuple[int, int], list[dict]] = {}
    for i in ideas:
        cells.setdefault((i["scores"]["difficulty"], i["scores"]["novelty"]), []).append(i)

    chip_w, chip_h, gap, per_row = 40, 18, 5, 4
    cell_w = per_row * chip_w + (per_row - 1) * gap + 20
    row_h = {}
    for n in range(1, 6):
        most = max((len(cells.get((d, n), [])) for d in range(1, 6)), default=0)
        rows = max(1, -(-most // per_row))
        row_h[n] = max(56, rows * (chip_h + gap) - gap + 22)

    left, top = 86, 96
    plot_w = cell_w * 5
    plot_h = sum(row_h.values())
    width, height = left + plot_w + 24, top + plot_h + 70

    p = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}" role="img" aria-labelledby="t d">',
         '<title id="t">Every idea by difficulty and novelty</title>',
         f'<desc id="d">Unit chart of {len(ideas)} agentic iOS app ideas. Horizontal axis: difficulty 1 to 5. Vertical axis: novelty 1 to 5. Each chip is one idea, colored and prefixed by tier. The full table is in ideas/README.md.</desc>',
         svg_style(),
         f'<rect class="bg" x="0" y="0" width="{width}" height="{height}" rx="12"/>',
         f'<text x="24" y="36" class="title">Where the ideas sit: difficulty × novelty</text>',
         f'<text x="24" y="58" class="sub">Each chip is one idea. Look up an ID in the index. Top-right is hard and new; bottom-left is easy and crowded.</text>']
    p += legend(24, 84)

    # grid: rows from novelty 5 (top) to 1 (bottom)
    y = top
    row_y = {}
    for n in range(5, 0, -1):
        row_y[n] = y
        y += row_h[n]
    for n in range(5, 0, -1):
        ry = row_y[n]
        p.append(f'<line class="grid" x1="{left}" y1="{ry}" x2="{left + plot_w}" y2="{ry}"/>')
        p.append(f'<text x="{left - 12}" y="{ry + row_h[n] / 2 + 4:.0f}" class="tick" text-anchor="end">{n}</text>')
    for d in range(0, 6):
        gx = left + d * cell_w
        p.append(f'<line class="grid" x1="{gx}" y1="{top}" x2="{gx}" y2="{top + plot_h}"/>')
    p.append(f'<line class="axis" x1="{left}" y1="{top + plot_h}" x2="{left + plot_w}" y2="{top + plot_h}"/>')
    for d in range(1, 6):
        p.append(f'<text x="{left + (d - 0.5) * cell_w:.0f}" y="{top + plot_h + 20}" class="tick" text-anchor="middle">{d}</text>')
    p.append(f'<text x="{left + plot_w / 2:.0f}" y="{top + plot_h + 46}" class="axis-label" text-anchor="middle">Difficulty →</text>')
    p.append(f'<text transform="translate(28 {top + plot_h / 2:.0f}) rotate(-90)" class="axis-label" text-anchor="middle">Novelty →</text>')

    for (d, n), group in cells.items():
        x0 = left + (d - 1) * cell_w + 10
        y0 = row_y[n] + 11
        for k, idea in enumerate(group):
            cx = x0 + (k % per_row) * (chip_w + gap)
            cy = y0 + (k // per_row) * (chip_h + gap)
            t = idea["tier"]
            p.append(f'<g><title>{html.escape(idea["id"] + " · " + idea["title"])}</title>'
                     f'<rect x="{cx}" y="{cy}" width="{chip_w}" height="{chip_h}" rx="4" class="fill-{t}"/>'
                     f'<text x="{cx + chip_w / 2}" y="{cy + 12.5}" text-anchor="middle" class="chip-text">{idea["id"]}</text></g>')
    p.append("</svg>")
    return "\n".join(p) + "\n"


def chart_category_tiers(data: dict) -> str:
    ideas = data["ideas"]
    counts = {c: {t: 0 for t in TIER_ORDER} for c in CATEGORIES}
    for i in ideas:
        counts[i["category"]][i["tier"]] += 1
    cats = [c for c in CATEGORIES if sum(counts[c].values())]
    cats.sort(key=lambda c: -sum(counts[c].values()))
    most = max(sum(counts[c].values()) for c in cats)

    label_w, left_pad, bar_h, row_gap = 190, 24, 18, 12
    plot_w = 520
    unit = plot_w / max(most, 1)
    top = 104
    height = top + len(cats) * (bar_h + row_gap) + 40
    width = left_pad + label_w + plot_w + 70

    p = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}" role="img" aria-labelledby="t2 d2">',
         '<title id="t2">Ideas per category, split by tier</title>',
         '<desc id="d2">Stacked horizontal bars. Each bar is a category; segments count ideas in each tier. Totals are printed at the bar end.</desc>',
         svg_style(),
         f'<rect class="bg" x="0" y="0" width="{width}" height="{height}" rx="12"/>',
         '<text x="24" y="36" class="title">Where the ideas cluster</text>',
         '<text x="24" y="58" class="sub">Ideas per category, split by tier. Long orange or green segments mark open ground.</text>']
    p += legend(24, 84)
    x_base = left_pad + label_w
    p.append(f'<line class="axis" x1="{x_base}" y1="{top - 6}" x2="{x_base}" y2="{height - 28}"/>')
    for r, c in enumerate(cats):
        y = top + r * (bar_h + row_gap)
        p.append(f'<text x="{x_base - 12}" y="{y + 13}" class="legend" text-anchor="end">{html.escape(c)}</text>')
        x = x_base
        segs = [(t, counts[c][t]) for t in TIER_ORDER if counts[c][t]]
        for k, (t, n) in enumerate(segs):
            w = n * unit - (2 if k < len(segs) - 1 else 0)
            last = k == len(segs) - 1
            if last:
                # square at the baseline side, 4px rounded data-end
                p.append(f'<path d="M{x:.1f},{y} h{w - 4:.1f} a4,4 0 0 1 4,4 v{bar_h - 8} a4,4 0 0 1 -4,4 h{-(w - 4):.1f} z" class="fill-{t}"><title>{html.escape(c)}: {n} {TIERS[t]["short"].lower()}</title></path>')
            else:
                p.append(f'<rect x="{x:.1f}" y="{y}" width="{w:.1f}" height="{bar_h}" class="fill-{t}"><title>{html.escape(c)}: {n} {TIERS[t]["short"].lower()}</title></rect>')
            x += n * unit
        p.append(f'<text x="{x + 8:.1f}" y="{y + 13}" class="val">{sum(counts[c].values())}</text>')
    p.append("</svg>")
    return "\n".join(p) + "\n"


# ----------------------------------------------------------------------- README

def readme_regions(data: dict) -> dict[str, str]:
    ideas = sorted(data["ideas"], key=sort_key)
    by_tier = {t: [i for i in ideas if i["tier"] == t] for t in TIER_ORDER}
    stats = ["| Tier | Ideas | What it means |", "|---|---|---|"]
    for t in TIER_ORDER:
        stats.append(f"| **{TIERS[t]['prefix']} · {TIERS[t]['name']}** | [{len(by_tier[t])}](ideas/README.md#{TIERS[t]['name'].lower().replace(' ', '-')}-{len(by_tier[t])}) | {TIERS[t]['blurb']} |")
    stats.append(f"| **Total** | **{len(ideas)}** | across {len({i['category'] for i in ideas})} categories |")

    flagship = [i for i in ideas if i.get("flagship")]
    picks = ["| | Idea | Tier | Why it's interesting |", "|---|---|---|---|"]
    for i in flagship:
        picks.append(f"| {i['id']} | [**{i['title']}**](ideas/{i['tier']}/{i['id']}-{i['slug']}.md)<br/><sub>{i['tagline']}</sub> "
                     f"| {TIERS[i['tier']]['short']} | {i.get('why_flagship', '')} |")

    per_tier = []
    for t in TIER_ORDER:
        per_tier += [f"### {TIERS[t]['prefix']} · {TIERS[t]['name']}", "", f"_{TIERS[t]['blurb']}_", ""]
        per_tier += [f"- **[{i['id']}](ideas/{t}/{i['id']}-{i['slug']}.md) {i['title']}** — {i['tagline']}" for i in by_tier[t]]
        per_tier.append("")
    return {"stats": "\n".join(stats), "flagships": "\n".join(picks), "all-ideas": "\n".join(per_tier).rstrip()}


def splice(text: str, regions: dict[str, str]) -> str:
    for name, body in regions.items():
        pat = re.compile(rf"(<!-- BEGIN GENERATED:{re.escape(name)} -->).*?(<!-- END GENERATED:{re.escape(name)} -->)", re.S)
        if not pat.search(text):
            raise SystemExit(f"README.md is missing the GENERATED:{name} markers")
        text = pat.sub(lambda m: f"{m.group(1)}\n{body}\n{m.group(2)}", text)
    return text


# -------------------------------------------------------------------------- main

def outputs(data: dict) -> dict[Path, str]:
    by_id = {i["id"]: i for i in data["ideas"]}
    files: dict[Path, str] = {}
    for idea in data["ideas"]:
        files[card_path(idea)] = render_card(idea, by_id)
    files[ROOT / "ideas" / "README.md"] = render_index(data)
    files[ROOT / "assets" / "charts" / "difficulty-novelty.svg"] = chart_difficulty_novelty(data)
    files[ROOT / "assets" / "charts" / "category-tiers.svg"] = chart_category_tiers(data)
    readme = ROOT / "README.md"
    files[readme] = splice(readme.read_text(encoding="utf-8"), readme_regions(data))
    return files


def main() -> int:
    check = "--check" in sys.argv
    data = load()
    errs = validate(data)
    if errs:
        print("data/ideas.json has problems:\n  " + "\n  ".join(errs), file=sys.stderr)
        return 1
    files = outputs(data)
    stale = []
    expected_cards = {p for p in files if p.parent.parent == ROOT / "ideas"}
    for tier in TIER_ORDER:
        d = ROOT / "ideas" / tier
        if d.exists():
            for f in d.glob("*.md"):
                if f not in expected_cards:
                    stale.append(f)
                    if not check:
                        f.unlink()
    for path, content in files.items():
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        stale.append(path)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if check and stale:
        print("Outputs are stale; run python3 scripts/build.py:\n  " + "\n  ".join(str(p.relative_to(ROOT)) for p in stale), file=sys.stderr)
        return 1
    print(f"{'Checked' if check else 'Built'} {len(data['ideas'])} ideas, {len(files)} files ({len(stale)} changed).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
